/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { userOutputSchema, userCreateSchema, userUpdateInputSchema } from "/Users/selim/Desktop/study/monorepo/apps/server/src/users/./users.schema";
import { signupSchema, signupOutputSchema, confirmOtpSchema, messageOutputSchema, loginSchema, loginOutputSchema, refreshSchema, tokensOutputSchema } from "/Users/selim/Desktop/study/monorepo/apps/server/src/auth/./auth.schema";

const appRouter = t.router({
  users: t.router({
    getAll: publicProcedure
      .output(z.array(userOutputSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findOne: publicProcedure
      .input(z.object({ id: z.string() }))
      .output(userOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(userCreateSchema)
      .output(userOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure
      .input(userUpdateInputSchema)
      .output(userOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure
      .input(z.object({ id: z.string() }))
      .output(z.boolean())
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  auth: t.router({
    signup: publicProcedure
      .input(signupSchema)
      .output(signupOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    confirm: publicProcedure
      .input(confirmOtpSchema)
      .output(messageOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    login: publicProcedure
      .input(loginSchema)
      .output(loginOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    refresh: publicProcedure
      .input(refreshSchema)
      .output(tokensOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
